##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/geocien1/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
